ALTER TABLE public.candidate_photos
  ADD COLUMN IF NOT EXISTS top7_zoom NUMERIC(4, 2) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS top7_offset_x NUMERIC(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS top7_offset_y NUMERIC(5, 2) NOT NULL DEFAULT 0;
